<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
      <TargetFramework>$(SilkTargetFramework)</TargetFramework>
      <RootNamespace>Silk.NET.GLFW</RootNamespace>
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\..\Native\Silk.NET.GLFW.Native\Silk.NET.GLFW.Native.csproj" />
    </ItemGroup>

    <Import Project="..\..\..\build\props\bindings.props" />
</Project>
