<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
      <TargetFramework>$(SilkTargetFramework)</TargetFramework>
      <RootNamespace>Silk.NET.GLFW</RootNamespace>
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>
    
    <ItemGroup>
      <!-- 中身は upstream と同一バイナリなのでフォークせず本家を使う -->
      <PackageReference Include="Ultz.Native.GLFW" Version="3.4.0" />
    </ItemGroup>

    <Import Project="..\..\..\build\props\bindings.props" />
</Project>
