<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\..\build\props\common.props" />

  <PropertyGroup>
    <TargetFramework>$(SilkTargetFramework)</TargetFramework>
    <PackageId>Ultz.Native.SDL</PackageId> <!-- TODO change this in 3.0 -->
    <PackageVersion>2.32.10</PackageVersion>
    <Authors>.NET Foundation and Contributors</Authors>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    <PackageLicenseExpression>Zlib</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/dotnet/Silk.NET</PackageProjectUrl>
    <Description>Multi-platform native library for SDL.</Description>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/libsdl-org/SDL</RepositoryUrl>
  </PropertyGroup>

</Project>
