<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(SilkTargetFramework)</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Silk.NET.Windowing.Common\Silk.NET.Windowing.Common.csproj" />
    </ItemGroup>

    <Import Project="..\..\..\..\build\props\common.props" />
</Project>
