<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
      <TargetFramework>$(SilkTargetFramework)</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Deterministic>true</Deterministic>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <Import Project="..\..\..\build\props\bindings.props" />
</Project>
