<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(SilkTargetFramework)</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <!-- 中身は upstream と同一バイナリなのでフォークせず本家を使う -->
    <PackageReference Include="Silk.NET.Shaderc.Native" Version="2.23.0" />
  </ItemGroup>

  <Import Project="..\..\..\build\props\bindings.props" />
</Project>
