<Project>
    <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />
    <PropertyGroup>
        <SilkDescription>A small and portable mathematics and linear algebra library, useful in graphics and compute workloads.</SilkDescription>
    </PropertyGroup>
</Project>
