<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>$(SilkTargetFramework)</TargetFramework>
        <LangVersion>preview</LangVersion>
        <DefineConstants Condition="'$(TargetFramework)' == 'netcoreapp3.1' Or '$(TargetFramework)' == 'net5.0'">$(DefineConstants);MATHF</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="BenchmarkDotNet" Version="0.15.2" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Silk.NET.Maths\Silk.NET.Maths.csproj" />
    </ItemGroup>

</Project>
