<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(SilkTargetFramework)</TargetFramework>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <LangVersion>preview</LangVersion>
        <SilkPublicApiExempt>true</SilkPublicApiExempt>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.DotNet.PlatformAbstractions" Version="3.1.6" />
        <PackageReference Include="Microsoft.Extensions.DependencyModel" Version="9.0.9" />
    </ItemGroup>

    <Import Project="..\..\..\build\props\common.props" />

</Project>
